name: Ping Vercel API

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Make a request to Vercel API endpoint
        run: |
          curl -X GET https://crypto-price-tracker-lake.vercel.app/
